coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 85%
        threshold: 0%  # 严格不允许任何浮动
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 0%
        if_ci_failed: error

# 确保只关注业务代码
ignore:
  - "**/*_test.cc"

# 强制 Codecov 返回状态检查
codecov:
  require_ci_to_pass: true  # 要求所有 CI 任务通过

# 更严格的注释配置
comment:
  layout: "reach,diff,flags,tree,changes"
  behavior: once
  branches: null  # 应用到所有分支
